version: '3.8'
services:
  api-student-25:
    build: .
    ports:
      - "3025:3000"
    environment:
      DB_URL: mongodb://mongo-student-25:27042/CRMdb-student-25
      PORT: 3000
    depends_on:
      - mongo-student-25
  mongo-student-25:
    image: mongo:latest
    ports:
      - "27050:27042"
    volumes:
      - db-data-student-25:/data/db
volumes:
  db-data-student-25: